In [ ]:
!apt-get install swig -y
!pip3 install Cython numpy
# sometimes you have to run the next command twice on colab
# I haven't figured out why
!pip3 install auto-sklearn

Reading package lists... Done
Building dependency tree       
Reading state information... Done
swig is already the newest version (3.0.12-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.


In [ ]:
!curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   207  100   207    0     0   2325      0 --:--:-- --:--:-- --:--:--  2325


In [ ]:
newDf.loc[(newDf['PM10_deiktis'] == 1),'LOW1']='low1'
newDf.loc[(newDf['PM10_deiktis'] == 2),'LOW2']='low2'
newDf.loc[(newDf['PM10_deiktis'] == 3),'LOW3']='low3'
newDf.loc[(newDf['PM10_deiktis'] == 4),'MOD1']='mod1'
newDf.loc[(newDf['PM10_deiktis'] == 5),'MOD2']='mod2'
newDf.loc[(newDf['PM10_deiktis'] == 6),'MOD3']='mod3'
newDf.loc[(newDf['PM10_deiktis'] == 7),'HIGH1']='high1'
newDf.loc[(newDf['PM10_deiktis'] == 8),'HIGH2']='high2'
newDf.loc[(newDf['PM10_deiktis'] == 9),'HIGH3']='high3'
newDf.loc[(newDf['PM10_deiktis'] == 10),'VERYHIGH']='veryhigh'

newDf["PM10_deiktis"]= newDf[['LOW1','LOW2','LOW3','MOD1','MOD2','MOD3','HIGH1','HIGH2','HIGH3','VERYHIGH']].apply(lambda x: ''.join(x.dropna().astype(str)),axis=1)
newDf=newDf[['1','2','3','4','5','6','7','8','hours','days','months','WS','PM10_deiktis','Synt Xrhs']]

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
newDf = pd.read_csv('colab_dataset.csv')


In [ ]:
                                           #depedent variable
'''
from sklearn.model_selection import train_test_split

#------------------------------ Feature Scaling ------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()                                                           #standardisation
colNumber=8                                                                    
X_train.iloc[:, colNumber:] = sc.fit_transform(X_train.iloc[:, colNumber:].values)#Me tin fit_transform upologizw tin mesi timi kai tin tupiki apoklisi 
X_test.iloc[:, colNumber:] = sc.transform(X_test.iloc[:, colNumber:].values)'''

'\nfrom sklearn.model_selection import train_test_split\n\n#------------------------------ Feature Scaling ------------------------------\nfrom sklearn.preprocessing import StandardScaler\nsc = StandardScaler()                                                           #standardisation\ncolNumber=8                                                                    \nX_train.iloc[:, colNumber:] = sc.fit_transform(X_train.iloc[:, colNumber:].values)#Me tin fit_transform upologizw tin mesi timi kai tin tupiki apoklisi \nX_test.iloc[:, colNumber:] = sc.transform(X_test.iloc[:, colNumber:].values)'

In [ ]:
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

#categorical_data["PM10_deiktis"] = pd.to_numeric(categorical_data["PM10_deiktis"])
# Load data
#X, y = sklearn.datasets.load_digits(return_X_y=True)

print(newDf.head())
newDf.info()
newDf.loc[(newDf['PM10_deiktis'] == 1),'LOW1']='low1'
newDf.loc[(newDf['PM10_deiktis'] == 2),'LOW2']='low2'
newDf.loc[(newDf['PM10_deiktis'] == 3),'LOW3']='low3'
newDf.loc[(newDf['PM10_deiktis'] == 4),'MOD1']='mod1'
newDf.loc[(newDf['PM10_deiktis'] == 5),'MOD2']='mod2'
newDf.loc[(newDf['PM10_deiktis'] == 6),'MOD3']='mod3'
newDf.loc[(newDf['PM10_deiktis'] == 7),'HIGH1']='high1'
newDf.loc[(newDf['PM10_deiktis'] == 8),'HIGH2']='high2'
newDf.loc[(newDf['PM10_deiktis'] == 9),'HIGH3']='high3'
newDf.loc[(newDf['PM10_deiktis'] == 10),'VERYHIGH']='veryhigh'

newDf["PM10_deiktis"]= newDf[['LOW1','LOW2','LOW3','MOD1','MOD2','MOD3','HIGH1','HIGH2','HIGH3','VERYHIGH']].apply(lambda x: ''.join(x.dropna().astype(str)),axis=1)
newDf=newDf[['1','2','3','4','5','6','7','8','hours','days','months','WS','PM10_deiktis','Synt Xrhs']]



newDf['PM10_deiktis']=newDf.PM10_deiktis.astype('category')
print('category --------> ',newDf['PM10_deiktis'])
X= newDf.drop('PM10_deiktis',axis=1)  
y=newDf['PM10_deiktis'] 
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)

print('y train:',y_train)
print('x:',X_train)
df1=pd.DataFrame(y_train)
df2=pd.DataFrame(X_train)
print(df1.info())
print(df2.info())
print('The total number of null values in each column:')
print(df2.isnull().sum())
print(df1.isnull().sum())

print('y test',y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()                                                           #standardisation
colNumber=8                                                                    
X_train.iloc[:, colNumber:] = sc.fit_transform(X_train.iloc[:, colNumber:].values)#Me tin fit_transform upologizw tin mesi timi kai tin tupiki apoklisi 
X_test.iloc[:, colNumber:] = sc.transform(X_test.iloc[:, colNumber:].values)

X_train.infer_objects()

     1    2    3    4    5  ...  days  months   WS  PM10_deiktis  Synt Xrhs
0  0.0  0.0  0.0  0.0  1.0  ...   1.0     4.0  1.2           1.0       43.5
1  0.0  0.0  0.0  1.0  0.0  ...   1.0     4.0  1.0           1.0       43.5
2  0.0  0.0  0.0  0.0  1.0  ...   1.0     4.0  0.9           1.0       43.5
3  0.0  0.0  0.0  0.0  0.0  ...   1.0     4.0  1.5           1.0       43.5
4  0.0  0.0  0.0  1.0  0.0  ...   1.0     4.0  1.2           1.0       43.5

[5 rows x 14 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7752 entries, 0 to 7751
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   1             7752 non-null   float64 
 1   2             7752 non-null   float64 
 2   3             7752 non-null   float64 
 3   4             7752 non-null   float64 
 4   5             7752 non-null   float64 
 5   6             7752 non-null   float64 
 6   7             7752 non-null   float64 
 7   8            

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/p

1    2    3    4  ...      days    months        WS  Synt Xrhs
101   0.0  0.0  0.0  1.0  ... -1.183479 -0.632027 -1.032410  -1.628251
3943  1.0  0.0  0.0  0.0  ...  0.525429  0.214981 -0.960172   2.299127
3338  0.0  0.0  0.0  0.0  ...  1.322919 -1.479034 -0.021084   0.750302
7535  0.0  0.0  0.0  1.0  ...  0.411502  1.061989 -0.310034  -0.964469
4226  0.0  0.0  0.0  0.0  ... -1.639187 -0.067355 -0.598985  -0.322813
...   ...  ...  ...  ...  ...       ...       ...       ...        ...
905   0.0  0.0  0.0  0.0  ... -0.841697  0.497317  0.629054   0.661798
5192  0.0  0.0  0.0  1.0  ... -0.499916 -0.914363 -0.310034   0.009078
3980  0.0  0.0  0.0  1.0  ...  0.639356  0.214981  0.484579   2.299127
235   0.0  0.0  0.0  1.0  ... -0.613843 -0.632027 -0.165559  -1.628251
5157  0.0  0.0  0.0  1.0  ... -0.727770 -0.914363 -0.960172   0.009078

[5814 rows x 13 columns]

In [ ]:
!pip install auto-sklearn
import autosklearn.classification as ac

# configure auto-sklearn
automl = ac.AutoSklearnClassifier( time_left_for_this_task=120,per_run_time_limit=30 )
# train model(s)
automl.fit(X_train, y_train)

# evaluate
y_hat = automl.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_hat)
print("Test Accuracy score {0}".format(test_acc))
print("Test Accuracy score  {0}".format(test_acc*100),'%')

Test Accuracy score 0.7239422084623323
Test Accuracy score  72.39422084623322 %


In [ ]:
print(automl.sprint_statistics())

auto-sklearn results:
  Dataset name: 0f19e0caeda41829f67270226bdb66aa
  Metric: accuracy
  Best validation score: 0.710266
  Number of target algorithm runs: 9
  Number of successful target algorithm runs: 7
  Number of crashed target algorithm runs: 0
  Number of target algorithms that exceeded the time limit: 2
  Number of target algorithms that exceeded the memory limit: 0



In [ ]:
print(automl.show_models())

[(0.800000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'random_forest', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'one_hot_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'minority_coalescer', 'data_preprocessing:numerical_transformer:imputation:strategy': 'mean', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'standardize', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:random_forest:bootstrap': 'True', 'classifier:random_forest:criterion': 'gini', 'classifier:random_forest:max_depth': 'None', 'classifier:random_forest:max_features': 0.5, 'classifier:random_forest:max_leaf_nodes': 'None', 'classifier:random_forest:min_impurity_decrease': 0.0, 'classifier:random_forest:min_samples_leaf': 1, 'classifier:random_forest:min_samples_split': 2, 'classifier:random_forest:min_weight_fraction_leaf': 0.0, 'data_preprocessing:categorical_tran

In [ ]:
print('y pred:',y_hat)
print('y test:',y_test)
df1=pd.DataFrame(y_test)
df2=pd.DataFrame(X_train)
print(df1.info())
print(df2.info())

y pred: ['low2' 'low2' 'low1' ... 'low1' 'low1' 'low2']
y test: 6430    low2
863     low1
7001    low1
5781    low1
6977    low1
        ... 
6025    low2
5862    low1
1228    low1
5899    low1
6077    low2
Name: PM10_deiktis, Length: 1938, dtype: category
Categories (11, object): ['', 'high1', 'high2', 'high3', ..., 'mod1', 'mod2', 'mod3', 'veryhigh']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1938 entries, 6430 to 6077
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   PM10_deiktis  1938 non-null   category
dtypes: category(1)
memory usage: 17.4 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5814 entries, 101 to 5157
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   1          5814 non-null   float64
 1   2          5814 non-null   float64
 2   3          5814 non-null   float64
 3   4          5814 non-null   float64
 4   5  

In [ ]:
from IPython.display import display
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_hat)
print(cm)


[[ 11   0   0   0   1   1   0   0   0   0   0]
 [  0   1   0   0   0   1   4   0   1   0   0]
 [  0   0   0   0   1   1   2   1   3   0   0]
 [  0   1   0   0   1   0   0   0   0   0   0]
 [  0   0   0   0 909 125   5   0   0   0   0]
 [  0   0   0   0 206 444  36   2   2   1   0]
 [  0   0   0   0  15  70  34   3   4   1   0]
 [  0   0   0   0   3  15  10   0   0   0   0]
 [  0   0   0   0   1   0   6   0   2   1   0]
 [  0   1   0   0   0   4   3   0   0   1   0]
 [  0   1   0   0   0   0   2   0   0   0   1]]


In [ ]:

df = pd.read_csv('dateset_dataset.csv')
import matplotlib.pyplot as plt
compare_data = pd.DataFrame({'dates':df['datetime'],
                            'Actual PM10':y,
                            'Predicted PM10':automl.predict(X)})
compare_data.infer_objects()
#compare_data["Actual PM10"] = pd.to_numeric(compare_data["Actual PM10"])
compare_data["Predicted PM10"] = pd.to_numeric(compare_data["Predicted PM10"])
compare_data.set_index('dates',inplace=True)
compare_data['Predicted PM10'] = np.round(compare_data['Predicted PM10'],1)


#compare_data = compare_data.resample('D').mean()

with plt.style.context('fivethirtyeight'):
    plt.figure(figsize=(12,5))
    plt.scatter(compare_data.index,compare_data['Actual PM10'],s=15,label='Actual PM10',
               alpha=.6)
    plt.scatter(compare_data.index,compare_data['Predicted PM10'],s=15,label='Predicted PM10',
               alpha=.6)
    plt.legend()
    plt.title('Evaluating the model\n',
             fontsize=18)
    plt.xlabel('period',fontsize=15)
    plt.ylabel('PM10 concentration',fontsize=15)
    plt.show()       

ValueError: ignored